name: coffee_shop
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  equatable: ^2.0.7
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  provider: ^6.1.5+1
  readmore: ^3.0.0
  flutter_map: ^8.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.9.0
  flutter_gen_runner: ^5.12.0
flutter:


  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 800


