name: coffee_shop
description: "Kaffein: A premium coffee shop experience app. Explore local cafes, order your favorite beans, and find the perfect brew using maps and location services."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management & Logic
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.5
  provider: ^6.1.5+1
  equatable: ^2.0.7
  get_it: ^7.6.0
  injectable: ^2.3.2
  uuid: ^4.5.1

  # Navigation
  go_router: ^14.6.2

  # Networking & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^7.0.0

  # Storage
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  flutter_secure_storage: ^9.0.0

  # Maps & Location
  google_maps_flutter: ^2.13.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # UI & Animations
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  readmore: ^3.0.0
  badges: ^3.1.2
  shimmer: ^3.0.0

  # Models & JSON
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.9.0
  flutter_gen_runner: ^5.6.0
  injectable_generator: ^2.4.1
  retrofit_generator: ^10.2.0
  json_serializable: ^6.7.1
  freezed: ^3.2.3

  # App Icon & Splash Generator
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
# Configuration for App Icons (Kaffein)
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#C67C4E"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

# Configuration for Splash Screen (Kaffein)
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#1C1C1C"
  fullscreen: true
  
  android_12:
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    color_dark: "#1C1C1C"
    icon_background_color_dark: "#1C1C1C"
  
  android: true
  ios: true
  web: false


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 800